steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'fast_api/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/fastapi-backend',
      'fast_api'
    ]

images:
  - 'gcr.io/$PROJECT_ID/fastapi-backend'
